const taskForm=document.getElementById('taskForm'),taskInput=document.getElementById('taskInput'),taskList=document.getElementById('taskList'),totalTasksSpan=document.getElementById('totalTasks'),completedTasksSpan=document.getElementById('completedTasks'),filterBtns=document.querySelectorAll('.filter-btn');
let tasks=loadTasks(),currentFilter='all';
function loadTasks(){try{const saved=JSON.parse(localStorage.getItem('poketasks'));return Array.isArray(saved)?saved:[]}catch{return[]}}function saveTasks(){localStorage.setItem('poketasks',JSON.stringify(tasks))}
function createShootingStars(){const container=document.getElementById('shootingStarsContainer');for(let i=0;container&&i<4;i++){const star=document.createElement('div');star.className='shooting-star';star.style.left=`${Math.random()*100}%`;star.style.top=`${Math.random()*40}%`;star.style.animationDuration=`${3+Math.random()*3}s`;star.style.animationDelay=`${Math.random()*7}s`;container.appendChild(star)}}
function createParticles(){const container=document.getElementById('starsContainer'),colors=['#00f5ff','#ff00e6','#ffe600','#ff6b6b','#48dbfb'];for(let i=0;container&&i<45;i++){const particle=document.createElement('div'),size=2+Math.random()*4;particle.className='particle';particle.style.width=particle.style.height=`${size}px`;particle.style.left=`${Math.random()*100}%`;particle.style.background=colors[Math.floor(Math.random()*colors.length)];particle.style.boxShadow=`0 0 ${size*2}px ${particle.style.background}`;particle.style.animationDuration=`${9+Math.random()*12}s`;particle.style.animationDelay=`${Math.random()*10}s`;container.appendChild(particle)}}
function visibleTasks(){return currentFilter==='pending'?tasks.filter(t=>!t.completed):currentFilter==='completed'?tasks.filter(t=>t.completed):tasks}function renderTasks(){taskList.replaceChildren();const shown=visibleTasks();if(!shown.length){const message=document.createElement('li');message.className='task-item';message.style.justifyContent='center';message.style.color='var(--text-secondary)';message.textContent=currentFilter==='all'?'No hay tareas... ¡agrega una!':currentFilter==='pending'?'¡Todas las tareas están completadas!':'No hay tareas completadas aún.';taskList.appendChild(message)}else shown.forEach(t=>taskList.appendChild(createTaskElement(t)));updateStats()}
function createTaskElement(task){const item=document.createElement('li'),checkbox=document.createElement('input'),text=document.createElement('span'),remove=document.createElement('button');item.className=`task-item${task.completed?' completed':''}`;checkbox.type='checkbox';checkbox.className='task-checkbox pokeball-checkbox';checkbox.checked=task.completed;checkbox.setAttribute('aria-label',`Marcar ${task.text} como completada`);checkbox.addEventListener('change',()=>toggleTask(task.id));text.className='task-text';text.textContent=task.text;remove.className='task-delete';remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',`Eliminar ${task.text}`);remove.addEventListener('click',()=>deleteTask(task.id,item));item.append(checkbox,text,remove);return item}
function updateStats(){totalTasksSpan.textContent=`Total: ${tasks.length}`;completedTasksSpan.textContent=`Completadas: ${tasks.filter(t=>t.completed).length}`}function toggleTask(id){const task=tasks.find(t=>t.id===id);if(task){task.completed=!task.completed;saveTasks();renderTasks()}}function deleteTask(id,item){item.style.cssText+=';opacity:0;transform:translateX(25px) scale(.96);transition:.3s';setTimeout(()=>{tasks=tasks.filter(t=>t.id!==id);saveTasks();renderTasks()},300)}function addTask(text){tasks.unshift({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,text,completed:false});saveTasks();renderTasks()}function resetInput(){taskInput.removeAttribute('style');taskInput.placeholder='¿Qué tarea vas a capturar?'}function setFilter(filter){currentFilter=filter;filterBtns.forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderTasks()}
taskForm.addEventListener('submit',event=>{event.preventDefault();const text=taskInput.value.trim();if(!text){taskInput.style.cssText='border-color:#ff5777;box-shadow:0 0 18px rgba(255,87,119,.4);animation:shake .3s ease';taskInput.placeholder='Escribe una tarea primero';taskInput.focus();return}addTask(text);taskInput.value='';resetInput();taskInput.focus()});taskInput.addEventListener('input',resetInput);filterBtns.forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));createShootingStars();createParticles();renderTasks();
